-- MySQL Script generated by MySQL Workbench
-- 12/14/15 19:56:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ttprdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ttprdb` ;

-- -----------------------------------------------------
-- Schema ttprdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ttprdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `ttprdb` ;

-- -----------------------------------------------------
-- Table `ttprdb`.`Gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`Gender` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`Gender` (
  `GenderId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Gender` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`GenderId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`Race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`Race` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`Race` (
  `RaceId` BIGINT NOT NULL COMMENT '',
  `Race` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`RaceId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`BloodType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`BloodType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`BloodType` (
  `BloodTypeId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `BloodType` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`BloodTypeId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`Patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`Patients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`Patients` (
  `PatientId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `LastName` VARCHAR(50) NULL COMMENT '',
  `FirstName` VARCHAR(50) NULL COMMENT '',
  `Mrn` INT(10) UNSIGNED NULL COMMENT '',
  `Dob` DATE NULL COMMENT '',
  `BloodType` VARCHAR(20) NULL COMMENT '',
  `AdmissionDate` DATE NULL COMMENT '',
  `GenderId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `RaceId` BIGINT NOT NULL COMMENT '',
  `BloodTypeId` BIGINT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`PatientId`)  COMMENT '',
  CONSTRAINT `fk_Patients_Gender`
    FOREIGN KEY (`GenderId`)
    REFERENCES `ttprdb`.`Gender` (`GenderId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patients_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `ttprdb`.`Race` (`RaceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patients_BloodType1`
    FOREIGN KEY (`BloodTypeId`)
    REFERENCES `ttprdb`.`BloodType` (`BloodTypeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Patients_Gender_idx` ON `ttprdb`.`Patients` (`GenderId` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_Patients_Race1_idx` ON `ttprdb`.`Patients` (`RaceId` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_Patients_BloodType1_idx` ON `ttprdb`.`Patients` (`BloodTypeId` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`Tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`Tests` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`Tests` (
  `TestId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Test` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`TestId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`Medications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`Medications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`Medications` (
  `MedicationId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Medication` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`MedicationId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`Therapies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`Therapies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`Therapies` (
  `TherapyId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Therapy` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`TherapyId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`PatientTests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`PatientTests` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`PatientTests` (
  `PatientTestId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `PatientId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `TestId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `TestDate` DATE NULL COMMENT '',
  PRIMARY KEY (`PatientTestId`, `PatientId`, `TestId`)  COMMENT '',
  CONSTRAINT `fk_PatientTests_Patients1`
    FOREIGN KEY (`PatientId`)
    REFERENCES `ttprdb`.`Patients` (`PatientId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PatientTests_Tests1`
    FOREIGN KEY (`TestId`)
    REFERENCES `ttprdb`.`Tests` (`TestId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PatientTests_Patients1_idx` ON `ttprdb`.`PatientTests` (`PatientId` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_PatientTests_Tests1_idx` ON `ttprdb`.`PatientTests` (`TestId` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`PatientMedicationList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`PatientMedicationList` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`PatientMedicationList` (
  `PatientMedicationListId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `PatientId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `MedicationId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `Dose` VARCHAR(45) NULL COMMENT '',
  `StartDate` DATE NULL COMMENT '',
  `EndDate` DATE NULL COMMENT '',
  PRIMARY KEY (`PatientMedicationListId`, `PatientId`, `MedicationId`)  COMMENT '',
  CONSTRAINT `fk_PatientMedicationList_Medications1`
    FOREIGN KEY (`MedicationId`)
    REFERENCES `ttprdb`.`Medications` (`MedicationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PatientMedicationList_Patients1`
    FOREIGN KEY (`PatientId`)
    REFERENCES `ttprdb`.`Patients` (`PatientId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PatientMedicationList_Medications1_idx` ON `ttprdb`.`PatientMedicationList` (`MedicationId` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_PatientMedicationList_Patients1_idx` ON `ttprdb`.`PatientMedicationList` (`PatientId` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ttprdb`.`PatientTherapies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttprdb`.`PatientTherapies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ttprdb`.`PatientTherapies` (
  `PatientTherapyId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `PatientId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `TherapyId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `StartDate` DATE NULL COMMENT '',
  `EndDate` DATE NULL COMMENT '',
  PRIMARY KEY (`PatientTherapyId`, `PatientId`, `TherapyId`)  COMMENT '',
  CONSTRAINT `fk_PatientTherapies_Patients1`
    FOREIGN KEY (`PatientId`)
    REFERENCES `ttprdb`.`Patients` (`PatientId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PatientTherapies_Therapies1`
    FOREIGN KEY (`TherapyId`)
    REFERENCES `ttprdb`.`Therapies` (`TherapyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PatientTherapies_Patients1_idx` ON `ttprdb`.`PatientTherapies` (`PatientId` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_PatientTherapies_Therapies1_idx` ON `ttprdb`.`PatientTherapies` (`TherapyId` ASC)  COMMENT '';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ttprdb`.`Gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `ttprdb`;
INSERT INTO `ttprdb`.`Gender` (`GenderId`, `Gender`) VALUES (DEFAULT, 'Male');
INSERT INTO `ttprdb`.`Gender` (`GenderId`, `Gender`) VALUES (DEFAULT, 'Female');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ttprdb`.`Race`
-- -----------------------------------------------------
START TRANSACTION;
USE `ttprdb`;
INSERT INTO `ttprdb`.`Race` (`RaceId`, `Race`) VALUES (DEFAULT, 'Caucasian');
INSERT INTO `ttprdb`.`Race` (`RaceId`, `Race`) VALUES (DEFAULT, 'African American');
INSERT INTO `ttprdb`.`Race` (`RaceId`, `Race`) VALUES (DEFAULT, 'Asian');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ttprdb`.`BloodType`
-- -----------------------------------------------------
START TRANSACTION;
USE `ttprdb`;
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'A+');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'B+');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'AB+');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'O+');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'A-');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'B-');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'AB-');
INSERT INTO `ttprdb`.`BloodType` (`BloodTypeId`, `BloodType`) VALUES (DEFAULT, 'O-');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ttprdb`.`Tests`
-- -----------------------------------------------------
START TRANSACTION;
USE `ttprdb`;
INSERT INTO `ttprdb`.`Tests` (`TestId`, `Test`) VALUES (DEFAULT, 'Platelet Count');
INSERT INTO `ttprdb`.`Tests` (`TestId`, `Test`) VALUES (DEFAULT, 'LDH');
INSERT INTO `ttprdb`.`Tests` (`TestId`, `Test`) VALUES (DEFAULT, 'Bilirubin');
INSERT INTO `ttprdb`.`Tests` (`TestId`, `Test`) VALUES (DEFAULT, 'Haptoglobin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ttprdb`.`Medications`
-- -----------------------------------------------------
START TRANSACTION;
USE `ttprdb`;
INSERT INTO `ttprdb`.`Medications` (`MedicationId`, `Medication`) VALUES (DEFAULT, 'Rituximab');
INSERT INTO `ttprdb`.`Medications` (`MedicationId`, `Medication`) VALUES (DEFAULT, 'Corticosteroid');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ttprdb`.`Therapies`
-- -----------------------------------------------------
START TRANSACTION;
USE `ttprdb`;
INSERT INTO `ttprdb`.`Therapies` (`TherapyId`, `Therapy`) VALUES (DEFAULT, 'Plasma Exchange');

COMMIT;

